server:
  port: 8888

spring:
  application:
    name: config-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file://${user.home}/Desktop/SpringCloud-MicroApplication-Config
        git:
          uri: https://github.com/saechimdaeki/SpringCloud-MicroApplication-Config
          default-label: main

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh

